name: recipes_book
description: Recipes Book
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  image_picker: ^1.0.7
  local_storage_recipes_api:
    path: packages/local_storage_recipes_api
  recipes_api:
    path: packages/recipes_api
  recipes_repository:
    path: packages/recipes_repository
  # --
  video_player: ^2.8.2
  mime: ^1.0.4
  # --

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
